analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3565674,"name"\:"ID_KatalonM2UappAndroid project","teamId"\:3579489,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3514150,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3579489,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=true
