<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_chat-fade</name>
   <tag></tag>
   <elementGuidId>e00f10cb-99ce-4aba-9b4f-36bf0fb04caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' chat-fade ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.chat-fade</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.chat-fade</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4bf13c9-85dd-49a9-9c1b-7b3dacb604d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chat-fade</value>
      <webElementGuid>005c8fd8-bb8b-4889-b6c2-7d3e64e16f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f9a2459b2403e8463daf22285b3cf590</value>
      <webElementGuid>42284dad-ef5d-4b5b-871f-de403ed771ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' chat-fade ')]</value>
      <webElementGuid>fb3dccba-f2a0-42ed-989b-5e4e861dc9f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' chat-fade ')]</value>
      <webElementGuid>05b9792b-5129-41bf-89e6-596126e46fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
