<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_chkAgree</name>
   <tag></tag>
   <elementGuidId>4e906887-a417-4970-b4d8-7986685bcbc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'chkAgree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chkAgree</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chkAgree</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>422d209c-c0d2-4c84-9c85-1b025de3417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chkAgree</value>
      <webElementGuid>93f338c7-551c-499f-9b5f-04fcff2872c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1a7ee1a2-fcc7-43d5-952a-0d686fe003c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkAgree</value>
      <webElementGuid>a70b3654-61ab-4040-bf4e-057f3649d655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>16a62b43-79af-4129-a40b-c92b7275f9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2266e8b97b99929feb947e9fb6bce7e7</value>
      <webElementGuid>79f59c18-4ece-4c99-acc9-d2170c0bec1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'chkAgree']</value>
      <webElementGuid>9b83feb5-c9c3-415a-b4e1-1d02b0cc8938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'chkAgree']</value>
      <webElementGuid>145d8ce2-667c-40b8-a471-59ec26660880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'chkAgree' and @type = 'checkbox' and @name = 'chkAgree']</value>
      <webElementGuid>f7a1d3e1-a4d9-4744-9364-55f3c988dead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
