<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_txtReferByTR</name>
   <tag></tag>
   <elementGuidId>fce9d32d-9866-428a-92f2-d413222950c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'txtReferByTR']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;txtReferByTR&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;txtReferByTR&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22d86396-6d15-4e2a-84e7-491021f4a90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input1</value>
      <webElementGuid>7900b5cd-e3fa-4021-a6ef-f772e3d67093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReferByTR</value>
      <webElementGuid>cbd456e8-55bf-43b7-b215-be3c9100f502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>415f351a-6fa1-416e-86a9-3c5702faa72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>53ea3ef9-5c0c-47da-86ac-b11899df2fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:onReferTRChange();</value>
      <webElementGuid>ca68c8f4-248c-4bd6-bbcb-3e157a0720b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									No
									Yes
								</value>
      <webElementGuid>aad88533-4571-467d-8306-e872093f4cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-76995a316ab9ab35323a8d3043cbbe1b</value>
      <webElementGuid>d0e80a81-dd98-4610-8430-0bb50b03bd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'txtReferByTR']</value>
      <webElementGuid>fa76b208-8542-4f83-a3fb-c63068dd232a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'txtReferByTR']</value>
      <webElementGuid>185383f0-aa8a-4762-a222-bdba8e3da65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'txtReferByTR' and (text() = '
									No
									Yes
								' or . = '
									No
									Yes
								')]</value>
      <webElementGuid>ecf8ca54-f98b-4b0e-ad39-d9bc86e93007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
